import type { Order, Product } from "@/lib/types";

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-001",
    customerName: "Fatima Al-Hinai",
    shippingAddress: "Al Khuwair, Building 14, Apt 302, Muscat",
    source: "instagram",
    status: "pending",
    shopLocation: "Muscat — Al Khuwair",
    createdAt: new Date(Date.now() - 8 * 60_000).toISOString(),
    items: [
      { id: "li-1", label: "Premium Abaya — Midnight Black", quantity: 1 },
      { id: "li-2", label: "Silk Hijab — Pearl White", quantity: 2 },
    ],
  },
  {
    id: "ord-002",
    customerName: "Ahmed Al-Balushi",
    shippingAddress: "Seeb City Center, Near Lulu, Seeb",
    source: "opensooq",
    status: "pending",
    shopLocation: "Seeb — City Center",
    createdAt: new Date(Date.now() - 22 * 60_000).toISOString(),
    items: [
      { id: "li-3", label: "Hoodie Blue — Size L", quantity: 2 },
      { id: "li-4", label: "Omani Cap — Traditional White", quantity: 1 },
    ],
  },
  {
    id: "ord-003",
    customerName: "Mariam Al-Rashdi",
    shippingAddress: "Qurum Heights, Villa 7, Muscat",
    source: "instagram",
    status: "pending",
    shopLocation: "Muscat — Qurum",
    createdAt: new Date(Date.now() - 45 * 60_000).toISOString(),
    items: [
      { id: "li-5", label: "Embroidered Abaya — Rose Gold", quantity: 1 },
    ],
  },
  {
    id: "ord-004",
    customerName: "Yousuf Al-Mamari",
    shippingAddress: "Mabela Industrial Area, Block 3, Seeb",
    source: "opensooq",
    status: "pending",
    shopLocation: "Seeb — Mabela",
    createdAt: new Date(Date.now() - 90 * 60_000).toISOString(),
    items: [
      { id: "li-6", label: "Samsung Galaxy Buds FE", quantity: 1 },
      { id: "li-7", label: "USB-C Fast Charger 45W", quantity: 1 },
    ],
  },
  {
    id: "ord-005",
    customerName: "Salma Al-Farsi",
    shippingAddress: "Ruwi High Street, Near Bank Muscat, Muscat",
    source: "instagram",
    status: "confirmed",
    shopLocation: "Muscat — Ruwi",
    createdAt: new Date(Date.now() - 3 * 60 * 60_000).toISOString(),
    items: [
      { id: "li-8", label: "Hoodie Grey — Size M", quantity: 1 },
    ],
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-001",
    title: "Premium Abaya — Midnight Black",
    sku: "ABY-BLK-001",
    price: 28.5,
    stock: 14,
    lowStockThreshold: 5,
    category: "Abayas",
    imageGradient: "from-slate-800 to-slate-950",
  },
  {
    id: "prod-002",
    title: "Embroidered Abaya — Rose Gold",
    sku: "ABY-RGD-002",
    price: 45.0,
    stock: 3,
    lowStockThreshold: 5,
    category: "Abayas",
    imageGradient: "from-rose-200 to-amber-100",
  },
  {
    id: "prod-003",
    title: "Silk Hijab — Pearl White",
    sku: "HJB-WHT-003",
    price: 8.75,
    stock: 22,
    lowStockThreshold: 8,
    category: "Hijabs",
    imageGradient: "from-gray-100 to-white",
  },
  {
    id: "prod-004",
    title: "Hoodie Blue — Size L",
    sku: "HDI-BLU-L",
    price: 12.5,
    stock: 7,
    lowStockThreshold: 5,
    category: "Hoodies",
    imageGradient: "from-blue-500 to-blue-700",
  },
  {
    id: "prod-005",
    title: "Hoodie Grey — Size M",
    sku: "HDI-GRY-M",
    price: 12.5,
    stock: 2,
    lowStockThreshold: 5,
    category: "Hoodies",
    imageGradient: "from-gray-400 to-gray-600",
  },
  {
    id: "prod-006",
    title: "Omani Cap — Traditional White",
    sku: "CAP-OM-WHT",
    price: 6.25,
    stock: 18,
    lowStockThreshold: 6,
    category: "Accessories",
    imageGradient: "from-stone-100 to-stone-300",
  },
  {
    id: "prod-007",
    title: "Samsung Galaxy Buds FE",
    sku: "ELC-SGB-FE",
    price: 32.9,
    stock: 5,
    lowStockThreshold: 4,
    category: "Electronics",
    imageGradient: "from-indigo-400 to-violet-600",
  },
  {
    id: "prod-008",
    title: "USB-C Fast Charger 45W",
    sku: "ELC-UC45W",
    price: 9.5,
    stock: 0,
    lowStockThreshold: 5,
    category: "Electronics",
    imageGradient: "from-emerald-400 to-teal-600",
  },
];
